### ISSUE TITLE
Issue with substitution method

### ISSUE THREAD

**Issue by dassbrothers** [pddenhar/Z3-IC3-PDR#2]
The test cases do not seem to run, and I am getting this error when using the substitution function. Can you please help me with this?

Traceback (most recent call last):
  File "sample.py", line 14, in <module>
    solver.run()
  File "/home/sourav/Z3-IC3-PDR/pdr.py", line 51, in run
    inv = self.checkForInduction()
  File "/home/sourav/Z3-IC3-PDR/pdr.py", line 64, in checkForInduction
    s.add(Not(substitute(frame, self.primeMap)))
  File "/home/sourav/.local/lib/python3.8/site-packages/z3/z3.py", line 8698, in substitute
    _z3_assert(all([isinstance(p, tuple) and is_expr(p[0]) and is_expr(p[1]) and p[0].sort().eq(
  File "/home/sourav/.local/lib/python3.8/site-packages/z3/z3.py", line 112, in _z3_assert
    raise Z3Exception(msg)
z3.z3types.Z3Exception: Z3 invalid substitution, expression pairs expected.

**Comment by yogurt-shadow** [comment]
@dassbrothers I have encounter the same problem, as someone mentioned at Z3Prover issues.
https://github.com/Z3Prover/z3/issues/1454

In fact, substitution inputs a formula and **a list of pairs**.
In this case, you must convert the map structure in to a list of pair like this way.
```python
tmp = []
for ele in self.primeMap:
    tmp.append(ele)
cubeprime = substitute(tcube.cube(), tmp)
```
Hope this will help you.

**Comment by dassbrothers** [comment]
@yogurt-shadow: I was getting the same error as an invalid substitution. So, I changed it to the following, which removed the error.

```
cubeprime = tcube.cube()
for key, value in self.primeMap.items():
    cubeprime = substitute(cubeprime, (key, value))
```
